services:
  rust-dev:
    build: .
    container_name: blue_scout
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    ports:
        - "3000:3000"  # 👈 Add this line
